---
abstract: 'Script to transliterate string.'
author:
  - 'Michal Josef Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
  Test::Output: 0
  Unicode::UTF8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-Translit-String
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  English: 0
  Error::Pure: 0.16
  Getopt::Std: 0
  Lingua::Translit: 0
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=App-Translit-String
  homepage: https://github.com/michal-josef-spacek/App-Translit-String
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/App-Translit-String
version: '0.06'
